build: resolve compiler warnings and errors with ptlib-2.18.8
The definition of PINDEX changed in ptlib commit
6629d94fcb3cfd369a9629399a20a217429b4d60 .

dle.cxx: In member function ‘int DLEData::GetDleData(void*, PINDEX)’:
dle.cxx:180:13: error: narrowing conversion of ‘-1’ from ‘int’ to
‘long unsigned int’ [-Wnarrowing]
  180 |       case -1:
pmutils.cxx: In member function ‘int ChunkStream::write(const void*, PINDEX)’:
pmutils.cxx:129:11: warning: comparison of integer expressions of
different signedness: ‘int’ and ‘PINDEX’ {aka ‘long unsigned int’} [-Wsign-compare]
  129 |   if (len > count)
pmutils.cxx: In member function ‘int ChunkStream::read(void*, PINDEX)’:
pmutils.cxx:145:11: warning: comparison of integer expressions of
different signedness: ‘int’ and ‘PINDEX’ {aka ‘long unsigned int’} [-Wsign-compare]
  145 |   if (len > count)